# NoLogger
NoLogger:
  github.io:
    link: https://nologger.github.io
  home:
    link: https://www.nologger.com
  admin:
    link: https://www.nologger.admin.com

# site.info
info:
  id: NoLogger.github.io
  title: NoLogger
  author: Kwangmin-Kim
  email: 1721046@gmail.com
  gitHub: noLogger