# info
title: noLogger 
email: 1721046@gmail.com
author: kwangmin_kim
description: >-
 KWANGMIN_KIM 
github_username:  noLogger 

# url
url: "https://nologger.github.io"
baseurl: ""

# nav (ui max 10)
docs:
  Home:
    title: Home
    url: /
  About:
    title: About
    url: /docs/about
  Jekyll:
    title: Jekyll
    url: /docs/jekyll
  ProgrammingMethodology:
    title: ProgrammingMethodology
    url: /docs/programmingMethodology